// Drawable Bible nouns for the "Sketch & Guess" game mode. The server only
// ever stores/transmits an INDEX into WORDS (see api/db.php's
// DRAW_WORD_BANK_SIZE and pickDrawWordChoices()) - mirrors js/impostor_data.js's
// PAIRS convention. api/drawing_words.php mirrors this exact list (same order)
// so the server can independently verify a guess without trusting the client -
// the secret word's index is deliberately hidden from guessers (unlike trivia
// questions, which ship in full to everyone), so correctness can't be judged
// client-side the way submit_answer.php does. Keep both files and
// DRAW_WORD_BANK_SIZE in sync if entries are added or removed.
(function () {
    const WORDS = [
        { word: 'Noah', aliases: [] },
        { word: 'Moses', aliases: [] },
        { word: 'David', aliases: [] },
        { word: 'Goliath', aliases: ['giant'] },
        { word: 'Samson', aliases: [] },
        { word: 'Jonah', aliases: [] },
        { word: 'Daniel', aliases: [] },
        { word: 'Solomon', aliases: [] },
        { word: 'Adam', aliases: [] },
        { word: 'Eve', aliases: [] },
        { word: 'Abraham', aliases: [] },
        { word: 'Joseph', aliases: [] },
        { word: 'Esther', aliases: [] },
        { word: 'Ruth', aliases: [] },
        { word: 'Peter', aliases: [] },
        { word: 'Paul', aliases: [] },
        { word: 'Judas', aliases: [] },
        { word: 'Ark', aliases: [] },
        { word: 'Cross', aliases: ['crucifix'] },
        { word: 'Crown', aliases: [] },
        { word: 'Sword', aliases: ['blade'] },
        { word: 'Shield', aliases: [] },
        { word: 'Harp', aliases: ['lyre'] },
        { word: 'Scroll', aliases: ['parchment'] },
        { word: 'Manna', aliases: [] },
        { word: 'Trumpet', aliases: ['horn'] },
        { word: 'Rainbow', aliases: [] },
        { word: 'Eden', aliases: ['garden'] },
        { word: 'Babel', aliases: ['tower'] },
        { word: 'Bethlehem', aliases: [] },
        { word: 'Jerusalem', aliases: [] },
        { word: 'Sinai', aliases: [] },
        { word: 'Egypt', aliases: [] },
        { word: 'Nazareth', aliases: [] },
        { word: 'Lion', aliases: [] },
        { word: 'Camel', aliases: [] },
        { word: 'Donkey', aliases: ['mule'] },
        { word: 'Whale', aliases: ['fish'] },
        { word: 'Serpent', aliases: ['snake'] },
        { word: 'Sheep', aliases: [] },
        { word: 'Cain', aliases: [] },
        { word: 'Abel', aliases: [] },
        { word: 'Seth', aliases: [] },
        { word: 'Enoch', aliases: [] },
        { word: 'Methuselah', aliases: [] },
        { word: 'Sarah', aliases: [] },
        { word: 'Hagar', aliases: [] },
        { word: 'Ishmael', aliases: [] },
        { word: 'Lot', aliases: [] },
        { word: 'Rebekah', aliases: [] },
        { word: 'Leah', aliases: [] },
        { word: 'Rachel', aliases: [] },
        { word: 'Laban', aliases: [] },
        { word: 'Esau', aliases: [] },
        { word: 'Jacob', aliases: [] },
        { word: 'Reuben', aliases: [] },
        { word: 'Levi', aliases: [] },
        { word: 'Judah', aliases: [] },
        { word: 'Benjamin', aliases: [] },
        { word: 'Miriam', aliases: [] },
        { word: 'Aaron', aliases: [] },
        { word: 'Joshua', aliases: [] },
        { word: 'Caleb', aliases: [] },
        { word: 'Rahab', aliases: [] },
        { word: 'Deborah', aliases: [] },
        { word: 'Gideon', aliases: [] },
        { word: 'Eli', aliases: [] },
        { word: 'Hannah', aliases: [] },
        { word: 'Saul', aliases: [] },
        { word: 'Jonathan', aliases: [] },
        { word: 'Abigail', aliases: [] },
        { word: 'Nathan', aliases: [] },
        { word: 'Absalom', aliases: [] },
        { word: 'Bathsheba', aliases: [] },
        { word: 'Elijah', aliases: [] },
        { word: 'Elisha', aliases: [] },
        { word: 'Jezebel', aliases: [] },
        { word: 'Ahab', aliases: [] },
        { word: 'Nebuchadnezzar', aliases: [] },
        { word: 'Belshazzar', aliases: [] },
        { word: 'Nehemiah', aliases: [] },
        { word: 'Mordecai', aliases: [] },
        { word: 'Haman', aliases: [] },
        { word: 'Job', aliases: [] },
        { word: 'Zechariah', aliases: [] },
        { word: 'John', aliases: [] },
        { word: 'Mary', aliases: [] },
        { word: 'Elizabeth', aliases: [] },
        { word: 'Lazarus', aliases: [] },
        { word: 'Martha', aliases: [] },
        { word: 'Altar', aliases: [] },
        { word: 'Temple', aliases: [] },
        { word: 'Tabernacle', aliases: [] },
        { word: 'Lampstand', aliases: [] },
        { word: 'Incense', aliases: [] },
        { word: 'Robe', aliases: [] },
        { word: 'Sandal', aliases: [] },
        { word: 'Rod', aliases: [] },
        { word: 'Net', aliases: [] },
        { word: 'Boat', aliases: [] },
        { word: 'Basket', aliases: [] },
        { word: 'Jar', aliases: [] },
        { word: 'Lamp', aliases: [] },
        { word: 'Candle', aliases: [] },
        { word: 'Tablet', aliases: ['tablets'] },
        { word: 'Coat', aliases: [] },
        { word: 'Cloak', aliases: [] },
        { word: 'Wineskin', aliases: [] },
        { word: 'Bread', aliases: ['loaf', 'loaves'] },
        { word: 'Wine', aliases: [] },
        { word: 'Oil', aliases: [] },
        { word: 'Coin', aliases: ['coins'] },
        { word: 'Purse', aliases: [] },
        { word: 'Sack', aliases: [] },
        { word: 'Tent', aliases: [] },
        { word: 'Pillar', aliases: [] },
        { word: 'Stone', aliases: [] },
        { word: 'Well', aliases: [] },
        { word: 'Vineyard', aliases: [] },
        { word: 'Fig', aliases: [] },
        { word: 'Grape', aliases: ['grapes'] },
        { word: 'Olive', aliases: [] },
        { word: 'Wheat', aliases: [] },
        { word: 'Barley', aliases: [] },
        { word: 'Honey', aliases: [] },
        { word: 'Furnace', aliases: [] },
        { word: 'Ladder', aliases: [] },
        { word: 'Chariot', aliases: [] },
        { word: 'Wheel', aliases: [] },
        { word: 'Yoke', aliases: [] },
        { word: 'Plow', aliases: [] },
        { word: 'Sickle', aliases: [] },
        { word: 'Winepress', aliases: [] },
        { word: 'Millstone', aliases: [] },
        { word: 'Anchor', aliases: [] },
        { word: 'Sail', aliases: [] },
        { word: 'Spear', aliases: [] },
        { word: 'Bow', aliases: [] },
        { word: 'Arrow', aliases: [] },
        { word: 'Helmet', aliases: [] },
        { word: 'Canaan', aliases: [] },
        { word: 'Goshen', aliases: [] },
        { word: 'Haran', aliases: [] },
        { word: 'Ur', aliases: [] },
        { word: 'Moab', aliases: [] },
        { word: 'Edom', aliases: [] },
        { word: 'Midian', aliases: [] },
        { word: 'Gilead', aliases: [] },
        { word: 'Jericho', aliases: [] },
        { word: 'Shiloh', aliases: [] },
        { word: 'Bethel', aliases: [] },
        { word: 'Hebron', aliases: [] },
        { word: 'Beersheba', aliases: [] },
        { word: 'Gaza', aliases: [] },
        { word: 'Damascus', aliases: [] },
        { word: 'Samaria', aliases: [] },
        { word: 'Galilee', aliases: [] },
        { word: 'Capernaum', aliases: [] },
        { word: 'Cana', aliases: [] },
        { word: 'Bethany', aliases: [] },
        { word: 'Gethsemane', aliases: [] },
        { word: 'Golgotha', aliases: [] },
        { word: 'Emmaus', aliases: [] },
        { word: 'Antioch', aliases: [] },
        { word: 'Ephesus', aliases: [] },
        { word: 'Corinth', aliases: [] },
        { word: 'Athens', aliases: [] },
        { word: 'Rome', aliases: [] },
        { word: 'Babylon', aliases: [] },
        { word: 'Nineveh', aliases: [] },
        { word: 'Tarshish', aliases: [] },
        { word: 'Sodom', aliases: [] },
        { word: 'Gomorrah', aliases: [] },
        { word: 'Ararat', aliases: [] },
        { word: 'Carmel', aliases: [] },
        { word: 'Tabor', aliases: [] },
        { word: 'Megiddo', aliases: [] },
        { word: 'Jezreel', aliases: [] },
        { word: 'Jordan', aliases: [] },
        { word: 'Patmos', aliases: [] },
        { word: 'Crete', aliases: [] },
        { word: 'Cyprus', aliases: [] },
        { word: 'Macedonia', aliases: [] },
        { word: 'Philippi', aliases: [] },
        { word: 'Thessalonica', aliases: [] },
        { word: 'Colossae', aliases: [] },
        { word: 'Sardis', aliases: [] },
        { word: 'Smyrna', aliases: [] },
        { word: 'Tyre', aliases: [] },
        { word: 'Sidon', aliases: [] },
        { word: 'Ox', aliases: [] },
        { word: 'Goat', aliases: [] },
        { word: 'Calf', aliases: [] },
        { word: 'Ram', aliases: [] },
        { word: 'Bull', aliases: [] },
        { word: 'Heifer', aliases: [] },
        { word: 'Lamb', aliases: [] },
        { word: 'Dove', aliases: [] },
        { word: 'Raven', aliases: [] },
        { word: 'Eagle', aliases: [] },
        { word: 'Sparrow', aliases: [] },
        { word: 'Owl', aliases: [] },
        { word: 'Vulture', aliases: [] },
        { word: 'Stork', aliases: [] },
        { word: 'Hawk', aliases: [] },
        { word: 'Locust', aliases: ['locusts'] },
        { word: 'Frog', aliases: ['frogs'] },
        { word: 'Gnat', aliases: [] },
        { word: 'Fly', aliases: [] },
        { word: 'Bee', aliases: [] },
        { word: 'Ant', aliases: [] },
        { word: 'Spider', aliases: [] },
        { word: 'Scorpion', aliases: [] },
        { word: 'Viper', aliases: [] },
        { word: 'Adder', aliases: [] },
        { word: 'Fish', aliases: [] },
        { word: 'Bear', aliases: [] },
        { word: 'Wolf', aliases: [] },
        { word: 'Fox', aliases: [] },
        { word: 'Jackal', aliases: [] },
        { word: 'Hyena', aliases: [] },
        { word: 'Leopard', aliases: [] },
        { word: 'Boar', aliases: [] },
        { word: 'Stag', aliases: [] },
        { word: 'Deer', aliases: [] },
        { word: 'Gazelle', aliases: [] },
        { word: 'Hare', aliases: [] },
        { word: 'Mouse', aliases: [] },
        { word: 'Mole', aliases: [] },
        { word: 'Bat', aliases: [] },
        { word: 'Leviathan', aliases: [] },
        { word: 'Behemoth', aliases: [] },
        { word: 'Worm', aliases: [] },
        { word: 'Moth', aliases: [] },
        { word: 'Hornet', aliases: [] },
        { word: 'Quail', aliases: [] },
        { word: 'Mule', aliases: [] },
        { word: 'Pigeon', aliases: [] },
        { word: 'Rooster', aliases: [] },
        { word: 'Peacock', aliases: [] },
    ];

    function normalize(str) {
        return String(str || '').toLowerCase().trim().replace(/[^a-z0-9 ]/g, '').replace(/\s+/g, ' ');
    }

    function matchesGuess(idx, guess) {
        const entry = WORDS[idx];
        if (!entry) return false;
        const g = normalize(guess);
        if (!g) return false;
        const candidates = [entry.word].concat(entry.aliases || []).map(normalize);
        return candidates.includes(g);
    }

    window.DrawingWords = { WORDS, normalize, matchesGuess };
})();
