/* ============================================================
   Bible Challenge Arena - Word Impostor Data
   Curated Bible word pairs for the Word Impostor game mode. Every
   crew member secretly gets wordA; the one Impostor secretly gets
   wordB instead - close enough to wordA that a vague clue could fit
   either, but different enough to give a sharp-eared crew a chance
   to catch the mismatch. Server only ever ships an index into this
   array (api/host_action.php hardcodes random_int(0, PAIRS.length-1)
   at game start) - never the word text itself - mirroring how
   QUESTION_DB/BookQuestions resolve question text from a db_index.
   ============================================================ */
const ImpostorData = (function () {
  const PAIRS = [
    { category: 'Characters', wordA: 'David', wordB: 'Goliath' },
    { category: 'Characters', wordA: 'Moses', wordB: 'Aaron' },
    { category: 'Characters', wordA: 'Cain', wordB: 'Abel' },
    { category: 'Characters', wordA: 'Jacob', wordB: 'Esau' },
    { category: 'Characters', wordA: 'Peter', wordB: 'Judas' },
    { category: 'Characters', wordA: 'Mary', wordB: 'Martha' },
    { category: 'Characters', wordA: 'Saul', wordB: 'David' },
    { category: 'Characters', wordA: 'Samson', wordB: 'Delilah' },
    { category: 'Characters', wordA: 'Noah', wordB: 'Lot' },
    { category: 'Characters', wordA: 'Joseph', wordB: 'Benjamin' },
    { category: 'Places', wordA: 'Jerusalem', wordB: 'Bethlehem' },
    { category: 'Places', wordA: 'Egypt', wordB: 'Babylon' },
    { category: 'Places', wordA: 'Eden', wordB: 'Sodom' },
    { category: 'Places', wordA: 'Nazareth', wordB: 'Capernaum' },
    { category: 'Places', wordA: 'Jericho', wordB: 'Jordan River' },
    { category: 'Places', wordA: 'Mount Sinai', wordB: 'Mount Carmel' },
    { category: 'Places', wordA: 'Galilee', wordB: 'Judea' },
    { category: 'Objects', wordA: 'Ark of the Covenant', wordB: "Noah's Ark" },
    { category: 'Objects', wordA: 'Manna', wordB: 'Quail' },
    { category: 'Objects', wordA: 'Staff', wordB: 'Rod' },
    { category: 'Objects', wordA: 'Cross', wordB: 'Crown of Thorns' },
    { category: 'Objects', wordA: 'Ten Commandments', wordB: 'Golden Calf' },
    { category: 'Events', wordA: 'The Flood', wordB: 'The Exodus' },
    { category: 'Events', wordA: 'The Crucifixion', wordB: 'The Resurrection' },
    { category: 'Events', wordA: 'Parting of the Red Sea', wordB: "Fall of Jericho's Walls" },
    { category: 'Events', wordA: 'The Last Supper', wordB: "The Lord's Prayer" },
    { category: 'Events', wordA: 'Tower of Babel', wordB: 'Garden of Eden' },
    { category: 'Animals', wordA: 'Lion', wordB: 'Bear' },
    { category: 'Animals', wordA: 'Whale', wordB: 'Dove' },
    { category: 'Characters', wordA: 'John the Baptist', wordB: 'John the Apostle' },

    // Characters
    { category: 'Characters', wordA: 'Abraham', wordB: 'Isaac' },
    { category: 'Characters', wordA: 'Isaac', wordB: 'Jacob' },
    { category: 'Characters', wordA: 'Elijah', wordB: 'Elisha' },
    { category: 'Characters', wordA: 'Solomon', wordB: 'Rehoboam' },
    { category: 'Characters', wordA: 'Samuel', wordB: 'Eli' },
    { category: 'Characters', wordA: 'Ruth', wordB: 'Naomi' },
    { category: 'Characters', wordA: 'Esther', wordB: 'Vashti' },
    { category: 'Characters', wordA: 'Daniel', wordB: 'Nebuchadnezzar' },
    { category: 'Characters', wordA: 'Jonah', wordB: 'Jeremiah' },
    { category: 'Characters', wordA: 'Job', wordB: 'Eliphaz' },
    { category: 'Characters', wordA: 'Gideon', wordB: 'Barak' },
    { category: 'Characters', wordA: 'Deborah', wordB: 'Jael' },
    { category: 'Characters', wordA: 'Boaz', wordB: 'Obed' },
    { category: 'Characters', wordA: 'Rahab', wordB: 'Achan' },
    { category: 'Characters', wordA: 'Ananias', wordB: 'Sapphira' },
    { category: 'Characters', wordA: 'Stephen', wordB: 'Philip' },
    { category: 'Characters', wordA: 'Barnabas', wordB: 'Silas' },
    { category: 'Characters', wordA: 'Timothy', wordB: 'Titus' },
    { category: 'Characters', wordA: 'Mary Magdalene', wordB: 'Mary, Mother of Jesus' },
    { category: 'Characters', wordA: 'Lazarus', wordB: 'Nicodemus' },
    { category: 'Characters', wordA: 'Nicodemus', wordB: 'Joseph of Arimathea' },
    { category: 'Characters', wordA: 'Pilate', wordB: 'Herod' },
    { category: 'Characters', wordA: 'Caiaphas', wordB: 'Annas' },
    { category: 'Characters', wordA: 'Zacchaeus', wordB: 'Bartimaeus' },
    { category: 'Characters', wordA: 'Thomas', wordB: 'Matthew' },
    { category: 'Characters', wordA: 'Ahab', wordB: 'Jezebel' },
    { category: 'Characters', wordA: 'Hezekiah', wordB: 'Manasseh' },
    { category: 'Characters', wordA: 'Josiah', wordB: 'Jehoiakim' },
    { category: 'Characters', wordA: 'Nehemiah', wordB: 'Ezra' },
    { category: 'Characters', wordA: 'Mordecai', wordB: 'Haman' },

    // Places
    { category: 'Places', wordA: 'Bethel', wordB: 'Shiloh' },
    { category: 'Places', wordA: 'Hebron', wordB: 'Beersheba' },
    { category: 'Places', wordA: 'Samaria', wordB: 'Sychar' },
    { category: 'Places', wordA: 'Tarsus', wordB: 'Antioch' },
    { category: 'Places', wordA: 'Damascus', wordB: 'Caesarea' },
    { category: 'Places', wordA: 'Patmos', wordB: 'Ephesus' },
    { category: 'Places', wordA: 'Corinth', wordB: 'Philippi' },
    { category: 'Places', wordA: 'Gethsemane', wordB: 'Golgotha' },
    { category: 'Places', wordA: 'Mount of Olives', wordB: 'Mount Tabor' },
    { category: 'Places', wordA: 'Red Sea', wordB: 'Dead Sea' },
    { category: 'Places', wordA: 'Negev Desert', wordB: 'Sinai Desert' },
    { category: 'Places', wordA: 'Joppa', wordB: 'Lydda' },
    { category: 'Places', wordA: 'Bethsaida', wordB: 'Chorazin' },
    { category: 'Places', wordA: 'Emmaus', wordB: 'Bethany' },
    { category: 'Places', wordA: 'Ur', wordB: 'Haran' },
    { category: 'Places', wordA: 'Padan Aram', wordB: 'Canaan' },
    { category: 'Places', wordA: 'Moab', wordB: 'Edom' },
    { category: 'Places', wordA: 'Ammon', wordB: 'Philistia' },
    { category: 'Places', wordA: 'Tyre', wordB: 'Sidon' },
    { category: 'Places', wordA: 'Babel', wordB: 'Nineveh' },

    // Objects
    { category: 'Objects', wordA: 'Mercy Seat', wordB: 'Altar of Incense' },
    { category: 'Objects', wordA: 'Bronze Serpent', wordB: 'Pillar of Salt' },
    { category: 'Objects', wordA: 'Shewbread', wordB: 'Lampstand' },
    { category: 'Objects', wordA: 'Ephod', wordB: 'Breastplate' },
    { category: 'Objects', wordA: 'Trumpet', wordB: "Ram's Horn" },
    { category: 'Objects', wordA: 'Sling', wordB: 'Spear' },
    { category: 'Objects', wordA: 'Sword', wordB: 'Shield' },
    { category: 'Objects', wordA: 'Robe of Many Colors', wordB: 'Purple Robe' },
    { category: 'Objects', wordA: 'Burning Bush', wordB: 'Pillar of Fire' },
    { category: 'Objects', wordA: 'Tablets of Stone', wordB: 'Scroll' },
    { category: 'Objects', wordA: 'Phylacteries', wordB: 'Prayer Shawl' },
    { category: 'Objects', wordA: 'Sackcloth', wordB: 'Ashes' },
    { category: 'Objects', wordA: 'Veil of the Temple', wordB: 'Curtain of the Tabernacle' },
    { category: 'Objects', wordA: 'Censer', wordB: 'Golden Bowl' },
    { category: 'Objects', wordA: 'Net', wordB: 'Fishing Boat' },
    { category: 'Objects', wordA: 'Mantle', wordB: 'Cloak' },
    { category: 'Objects', wordA: 'Thirty Pieces of Silver', wordB: "Potter's Field" },
    { category: 'Objects', wordA: 'Wedding Garment', wordB: 'Linen Cloth' },
    { category: 'Objects', wordA: 'Olive Branch', wordB: 'Fig Leaf' },
    { category: 'Objects', wordA: 'Jar of Oil', wordB: 'Jar of Flour' },

    // Events
    { category: 'Events', wordA: 'The Ascension', wordB: 'The Transfiguration' },
    { category: 'Events', wordA: 'The Baptism of Jesus', wordB: 'The Wedding at Cana' },
    { category: 'Events', wordA: 'The Sermon on the Mount', wordB: 'The Sermon on the Plain' },
    { category: 'Events', wordA: 'The Triumphal Entry', wordB: 'Cleansing of the Temple' },
    { category: 'Events', wordA: 'The Birth of Jesus', wordB: 'The Visit of the Magi' },
    { category: 'Events', wordA: 'The Day of Pentecost', wordB: 'The Feast of Tabernacles' },
    { category: 'Events', wordA: 'The Fall of Man', wordB: 'The Expulsion from Eden' },
    { category: 'Events', wordA: 'The Binding of Isaac', wordB: 'The Call of Abraham' },
    { category: 'Events', wordA: 'The Plagues of Egypt', wordB: 'The Passover' },
    { category: 'Events', wordA: 'Worship of the Golden Calf', wordB: 'Giving of the Law' },
    { category: 'Events', wordA: 'The Battle of Jericho', wordB: 'The Battle of Ai' },
    { category: 'Events', wordA: "David's Anointing", wordB: "Saul's Coronation" },
    { category: 'Events', wordA: "Elijah's Ascension", wordB: "Elisha's Calling" },
    { category: 'Events', wordA: 'The Fiery Furnace', wordB: "The Lion's Den" },
    { category: 'Events', wordA: 'The Writing on the Wall', wordB: 'The Fall of Babylon' },
    { category: 'Events', wordA: "Jonah's Storm", wordB: "Jonah's Preaching" },
    { category: 'Events', wordA: 'The Raising of Lazarus', wordB: "The Raising of Jairus' Daughter" },
    { category: 'Events', wordA: 'The Healing of the Blind Man', wordB: 'The Healing of the Lame Man' },
    { category: 'Events', wordA: 'The Feeding of the 5,000', wordB: 'The Feeding of the 4,000' },
    { category: 'Events', wordA: 'The Stoning of Stephen', wordB: 'The Conversion of Paul' },

    // Animals
    { category: 'Animals', wordA: 'Sheep', wordB: 'Goat' },
    { category: 'Animals', wordA: 'Ox', wordB: 'Donkey' },
    { category: 'Animals', wordA: 'Eagle', wordB: 'Vulture' },
    { category: 'Animals', wordA: 'Locust', wordB: 'Grasshopper' },
    { category: 'Animals', wordA: 'Ram', wordB: 'Lamb' },
    { category: 'Animals', wordA: 'Camel', wordB: 'Horse' },
    { category: 'Animals', wordA: 'Raven', wordB: 'Sparrow' },
    { category: 'Animals', wordA: 'Frog', wordB: 'Gnat' },
    { category: 'Animals', wordA: 'Behemoth', wordB: 'Leviathan' },
    { category: 'Animals', wordA: 'Scapegoat', wordB: 'Sacrificial Lamb' }
  ];

  return { PAIRS };
})();
